hoops:
- orientation:
    p: 45
    r: 0
    y: 0
  position:
    x: 5.0
    y: 0.0
    z: 3.0
  radius: 1.0
- orientation:
    p: 0
    r: 0
    y: 45
  position:
    x: 23.0
    y: 2.0
    z: 4.0
  radius: 1.2
- orientation:
    p: 0
    r: 0
    y: 0
  position:
    x: 47.0
    y: -2.0
    z: 4.0
  radius: 0.8
  