hoops:
  - position:
      x: 0.0
      y: 0.0
      z: 1.0
    orientation:
      r: 0
      p: 0
      y: 0
    radius: 1.0
  - position:
      x: 2.0
      y: 0.0
      z: 1.0
    orientation:
      r: 0
      p: 0
      y: 0
    radius: 1.0
  - position:
      x: -2.0
      y: 0.0
      z: 1.0
    orientation:
      r: 0
      p: 0
      y: 0
    radius: 1.0