hoops:
  - position:
      x: 0.0
      y: 0.0
      z: 1.0
    orientation:
      r: 0
      p: 45
      y: 0
    radius: 1.0
  - position:
      x: 2.0
      y: 1.0
      z: 1.5
    orientation:
      r: 0
      p: 0
      y: 30
    radius: 0.8
  - position:
      x: -1.0
      y: -1.0
      z: 2.0
    orientation:
      r: 30
      p: 0
      y: 0
    radius: 1.2