hoops:
  - position:
      x: 0.0
      y: 0.0
      z: 3.0
    orientation:
      r: 0
      p: 0
      y: 0
    radius: 1.0
  - position:
      x: 5.0
      y: 0.0
      z: 4.0
    orientation:
      r: 0
      p: 0
      y: 0
    radius: 0.8
  - position:
      x: 12.0
      y: 0.0
      z: 4.0
    orientation:
      r: 0
      p: 0
      y: 30
    radius: 0.8